### ISSUE TITLE
Running the sample on Android

### ISSUE THREAD

**Issue by smtabatabaie** [Clarifai/clarifai-csharp#2]
Hi, I opened the sample on Unity 2018 in windows and could predict with Unity editor. 
I tried to run the sample on my Android device but the same sample that works on Unity editor now doesn't run Android and gives me response code 404.
Is it possible to run Unity Clarifai on Android?
I'll appreciate if you can help me with this.
Thanks

**Comment by smtabatabaie** [comment]
I changed "Internet access" from "auto" to "require" and it seems solved for now.

**Comment by rok-povsic** [comment]
I'm glad you were able to solve this.
