### ISSUE TITLE
Client not working with Video

### ISSUE THREAD

**Issue by martonx** [Clarifai/clarifai-csharp#4]
Hi,

Please try your client with VideoUrl. It won't work, because of the response schema is different than Image response schema.

var returnObject = clarifaiClient.PublicModels.GeneralModel
                    .Predict(new ClarifaiURLVideo(signedURL))
                    //.Predict(new ClarifaiURLImage("https://samples.clarifai.com/metro-north.jpg"))
                    .ExecuteAsync()
                    .Result;

**Comment by rok-povsic** [comment]
Hi @martonx ,

to predict on a video, you have to use a _Video_ model. The general video model would be used with `Client.PublicModels.GeneralVideoModel`. Please use auto-completion to see all the available _Video_ models.

Here's a full example:

```php
var response = await Client.Predict<Frame>(
        Client.PublicModels.GeneralVideoModel.ModelID,
        new ClarifaiURLVideo("YOUR-VIDEO-URL"))
    .ExecuteAsync();

foreach (Frame frame in response.Get().Data)
{
    Console.WriteLine(frame.Index);
    foreach (Concept concept in frame.Concepts)
    {
        Console.WriteLine(concept.Name + " " + concept.Value);
    }
}
```

Hopefully this solves your issue.

Good luck,
Rok
