### ISSUE TITLE
1.4.0 package

### ISSUE THREAD

**Issue by cguedel** [Clarifai/clarifai-csharp#9]
Hi

We're trying to upgrade our code to work with the latest breaking changes announced to be deployed on the 27th of February. However, there is no updated SDK available, even though you bumped the version to 1.4.0, a corresponding nuget package is not around.

Could you please provide this?

Thank you

**Comment by rok-povsic** [comment]
Hey @cguedel unfortunately we're still trying to get back access to the nuget account. At this moment, the only way to access the latest code is to use it from this repository.

Note that the latest deployed nuget version will work fine for non-face-related models.

**Comment by cguedel** [comment]
Any ETA on this?

**Comment by rok-povsic** [comment]
@cguedel I've published the nupkg and dll [to Github](https://github.com/Clarifai/clarifai-csharp/releases/tag/1.4.0) which you can use to directly install the latest Clarifai release. If using .NET Core, [this](https://stackoverflow.com/questions/43400069/dotnet-add-package-with-local-package-file) and [this](https://stackoverflow.com/questions/40108106/using-external-dll-in-dot-net-core) might be helpful in how to do it.

Right now we're waiting for nuget support to get back the access. We'll deploy as soon as we have the access.

**Comment by cguedel** [comment]
any luck yet?

**Comment by rok-clarifai** [comment]
@cguedel We've gotten back the access and released version 1.4.0 to NuGet. Thanks for your patience.
